### ISSUE TITLE
ReferenceError: host is not defined

### ISSUE THREAD

**Issue by sgofferj** [ampledata/node-red-contrib-tcp-tls#2]
```
15 Aug 14:37:07 - [info] [tcp tls in:d7e812b8.371f5] connected to 192.168.10.201:8089
15 Aug 14:37:07 - [red] Uncaught Exception:
15 Aug 14:37:07 - ReferenceError: host is not defined
    at TLSSocket.<anonymous> (/data/node_modules/node-red-contrib-tcp-tls/tcp-tls.js:121:64)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1109:12)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:666:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.3.5 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
```

Trying to connect to local taky server with "verify host certificate" turned off in TLS settings. When verify host certificate is turned on, the connect fails with 
```
15 Aug 14:33:46 - [info] [tcp tls in:d7e812b8.371f5] Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: 192.168.10.201 is not in the cert's list: 
```

**Comment by sgofferj** [comment]
in tcp-tls.js replace line 121:
old:
```
                        text: RED._("status.connected", {host: host, port: port}),
```
new:
```
                        text: RED._("status.connected", {host: node.host, port: node.port}),
```

**Comment by ampledata** [comment]
Same problem line 351
